name: 🐛 Bug report
description: Report a bug to help us improve the app.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a feature, please make sure that you have read through our existing [issues](https://github.com/molsrg/gym-bro-app/issues?q=is%3Aissue%20is%3Aopen%20sort%3Aupdated-desc%20label%3Abug).
  - type: input
    id: version
    attributes:
      label: Version
      description: You can look in the Telegram app to fill out this section
      placeholder: v0.1.1
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description.
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context or screenshots here.
